[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build]
cmds = [
  "cd backend",
  "npm install",
  "npx prisma generate",
  "npx @nestjs/cli build"
]

[start]
cmd = "cd backend && npm run start:prod"
